expr =  { "(" ~ polynomial ~ ")" ~ op ~ "(" ~ polynomial ~ ")" }
op   = _{ add }
add  =  { "+" }

sign       =  { "+" | "-" }
number     =  { ASCII_DIGIT+ ~ ("." ~ ASCII_DIGIT+)? }
var        =  { ASCII_ALPHA }
term       =  { sign? ~ (number | var)+ }
polynomial =  { term ~ (WHITESPACE* ~ term)* }
file       =  { SOI ~ ((expr | polynomial) ~ NEWLINE)* ~ (expr | polynomial) ~ NEWLINE? ~ EOI }
WHITESPACE = _{ " " }
